services:
  postgres:
    restart: always
    image: postgres:18.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: archischema
    ports:
      - "5432:5432"
